// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlXbAnu_DC4LMbBViETL1NThd7fNKffOQ',
    appId: '1:552844690815:web:cbac84f34e85d4835f464a',
    messagingSenderId: '552844690815',
    projectId: 'football-tournament-mana-d5086',
    authDomain: 'football-tournament-mana-d5086.firebaseapp.com',
    storageBucket: 'football-tournament-mana-d5086.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvNhgLt-PcgaHECFIo17zqGdBJyKmHkwI',
    appId: '1:552844690815:android:ca59126d1dbc7cf45f464a',
    messagingSenderId: '552844690815',
    projectId: 'football-tournament-mana-d5086',
    storageBucket: 'football-tournament-mana-d5086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCLMStdl2VvMxH06_vgW4Biiyrn7NdoTQ',
    appId: '1:552844690815:ios:aef355a7c34525175f464a',
    messagingSenderId: '552844690815',
    projectId: 'football-tournament-mana-d5086',
    storageBucket: 'football-tournament-mana-d5086.firebasestorage.app',
    iosBundleId: 'com.example.footballTournamentManagerApp',
  );
}
